export interface Recipe {
    id: number,
    title: string,
    summary: string,
    image: any,
    time: number,
    porsion: number,
    complexity: number,
    calories: number,
    fats: number,
    proteins: number,
    carbohydrates: number,
    publish: string,
    rating: number,
    user_id: number,
    category_id: number,
    sub_category_id: number,
    country_id: number,
}
