export interface Recipe {
    id: number,
    title: string,
    slug: string,
    summary: string,
    image: any,
    time: number,
    porsion: number,
    complexity: number,
    calories: number,
    fats: number,
    proteins: number,
    carbohydrates: number,
    publish: string,
    rating: number,
    user_id: number,
    category_id: number,
    sub_category_id: number,
    country_id: number,
    likes: number,
    liked: any,
    category: {
        id: number,
        name: string,
        slug: string,
    },
    country: {
        id: number,
        name: string,
    },
    ingredients: [{
        id: number,
        name: string,
        image: string,
        calories: number,
        fats: number,
        proteins: number,
        carbohydrates: number,   
    }],
    recipes_ingredients: [{
        id: number,
        amount: number,
        ingredient_id: number,
        unit: string,
    }]
}
